/**
 * Emit the client search index.
 *
 *   npx tsx scripts/build-search-index.ts
 *
 * A trimmed copy of the catalogue — slug, title, brand, department, flavours,
 * price, thumbnail — for the typeahead to score against in the browser.
 *
 * It is a generated module rather than a prop because `<SearchBox>` lives in
 * the site header: passing the index down would serialise all 175 documents
 * into the RSC payload of every single page. As a module it lands in the JS
 * bundle once and is cached across navigations.
 *
 * Run after fetch-images.ts, which is where the thumbnails come from.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

type Model = {
  slug: string;
  title: string;
  brand?: string;
  category: string | null;
  regulatoryClass: string;
  publishable: boolean;
  priceCents: number | null;
  flavors: { value: string; family: string | null }[];
};

const catalog: Model[] = JSON.parse(
  readFileSync(resolve("src/lib/commerce/catalog.generated.json"), "utf8"),
);
const images: Record<string, { src: string }> = JSON.parse(
  readFileSync(resolve("src/lib/commerce/images.generated.json"), "utf8"),
);

/* departmentFor lives in the adapter and is not importable from a script
   without pulling the whole module graph, so the mapping is mirrored here.
   It reads fields off the model directly — an earlier version indexed a second
   copy of the array with the filtered loop counter, which silently shifted
   every department by the number of unpublishable models skipped before it and
   filed the Acid cigars under accessories. */

const docs = catalog
  .filter((m) => m.publishable && m.priceCents !== null)
  .map((m) => {
    const c = m.category ?? "";
    const dept = /glass|bong|pipe/i.test(c)
      ? "glass"
      : /hookah|shisha/i.test(c)
        ? "hookah"
        : /^cigar$|cigarillo/i.test(c)
          ? "cigars"
          : /cigarette/i.test(c)
            ? "cigarettes"
            : /vape|juul|vuse|njoy|juice/i.test(c)
              ? "vape"
              : /pouch|lighter|torch|papper|paper|leaf|rolling|smoke part|part of wd/i.test(c)
                ? "accessories"
                : m.regulatoryClass === "cigar"
                  ? "cigars"
                  : m.regulatoryClass === "cigarette"
                    ? "cigarettes"
                    : m.regulatoryClass === "hookah"
                      ? "hookah"
                      : m.regulatoryClass === "ends"
                        ? "vape"
                        : "accessories";

    /* Must mirror `toDoc` exactly: flavour values PLUS the dominant family.
       Omitting the family made the client index find 82 matches for "mint"
       where the server found 90 — the typeahead and the page it links to
       disagreeing, which is the one thing this index must never do. */
    const counts = new Map<string, number>();
    for (const f of m.flavors ?? []) {
      if (f.family) counts.set(f.family, (counts.get(f.family) ?? 0) + 1);
    }
    let dominant: string | undefined;
    let best = 0;
    for (const [k, v] of counts) if (v > best) ((dominant = k), (best = v));

    const allFlavors = new Set([
      ...(m.flavors ?? []).map((f) => f.value).filter(Boolean),
      ...(dominant ? [dominant] : []),
    ]);
    const flavors = [...allFlavors].slice(0, 12);

    return {
      slug: m.slug,
      title: m.title,
      ...(m.brand ? { brand: m.brand } : {}),
      department: dept,
      flavors,
      nf: allFlavors.size,
      price: m.priceCents as number,
      ...(images[m.slug] ? { img: images[m.slug].src } : {}),
    };
  })
  .sort((a, b) => a.slug.localeCompare(b.slug));

const out = `// GENERATED by scripts/build-search-index.ts — do not edit.
// ${docs.length} products, for the client-side typeahead.
import type { SearchDoc } from "./search";

export const SEARCH_DOCS: SearchDoc[] = ${JSON.stringify(docs)};
`;

const path = resolve("src/lib/search-index.ts");
writeFileSync(path, out);
console.log(`${docs.length} products -> ${path}`);
console.log(`${Math.round(out.length / 1024)} KB uncompressed`);
